version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   # RabbitMQ message broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: python-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development  # Enable hot reloading
    volumes:
      - ./src/api:/app/api  # Mount for development
      - ./data/downloads:/app/data/downloads
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vite-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
